export type Tag =
  | "Angular"
  | "Angular Material UI"
  | "Bootstrap"
  | "Chakra UI"
  | "CSS"
  | "dbdiagram.io"
  | "Figma"
  | "Heroku"
  | "HTML"
  | "JavaScript"
  | "JQuery"
  | "Material UI"
  | "Netlify"
  | "Next JS"
  | "Next UI"
  | "Open Graph"
  | "PostgreSQL"
  | "Rails"
  | "React"
  | "React Icons"
  | "React JS"
  | "Redux"
  | "Render"
  | "Ruby"
  | "Ruby on Rails"
  | "Sass"
  | "SCSS"
  | "SQL"
  | "SQLite"
  | "Supabase"
  | "Swiper JS"
  | "Tailwind CSS"
  | "Tremor"
  | "TypeScript"
  | "Vercel"
  | "Vanilla JS"
  | "Web Accessibility";
